repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17  # Use the ref you want to point at
    hooks:
    -   id: mdformat
        # Optionally add plugins
        args: ["--number"]
        additional_dependencies:
        -   mdformat-black
        -   mdformat-myst
        -   mdformat-frontmatter
